version: 2.1

orbs:
  macos: circleci/macos@2.4.1

jobs:
  build:
    parameters:
      runs:
        type: integer
    macos:
      xcode: "15.2.0"
    resource_class: macos.m1.medium.gen1
    steps:
      - macos/preboot-simulator:
          device: "iPhone SE (3rd generation)"
          platform: "iOS Simulator"
          version: "17.2"
      - checkout
      - run:
          name: build_and_test
          command: |
            xcodebuild -project CircleCITest/CircleCITest.xcodeproj \
              -scheme CircleCITest \
              -sdk iphonesimulator \
              -derivedDataPath ".build" \
              -destination "platform=iOS Simulator,OS=17.2,name=iPhone SE (3rd generation)" \
              test
      - run:
          name: Zip test results
          command: |
            find .build -iname "*.xcresult" -exec zip -qr ./test.xcresult.zip {} \;
          when: always
      - store_artifacts:
          path: test.xcresult.zip
      - store_artifacts:
          path: ~/Library/Logs/DiagnosticReports
      - store_artifacts:
          path: ~/Library/Logs/CoreSimulator
      - store_artifacts:
          path: ~/Library/Logs/CrashReporter

workflows:
  pull-request:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
          matrix:
            parameters:
              runs: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master
          matrix:
            parameters:
              runs: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
